
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Piman Angkurasri  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Ubon Ratchathani , TH


## Social Profiles
facebook: http://https://www.facebook.com/profile.php?id=100009899222250  ## your facebook account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
